"""add User

Revision ID: 2513043489df
Revises: 14a8923cf673
Create Date: 2018-05-03 15:44:47.433787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2513043489df'
down_revision = '14a8923cf673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
