"""..

Revision ID: ad5e12d4c9ec
Revises: 
Create Date: 2018-05-14 17:19:13.650181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5e12d4c9ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('avatar', sa.String(length=64), nullable=True))
    op.add_column('nodes', sa.Column('header', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'header')
    op.drop_column('nodes', 'avatar')
    # ### end Alembic commands ###
