"""..

Revision ID: d05db70a7c31
Revises: 13b7fa87fac3
Create Date: 2018-05-14 15:27:45.858002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05db70a7c31'
down_revision = '13b7fa87fac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('avatar', sa.String(length=64), nullable=True))
    op.add_column('nodes', sa.Column('header', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'header')
    op.drop_column('nodes', 'avatar')
    # ### end Alembic commands ###
